/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupo3_mat.edEXT.Presentacion.Pantallas;

import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.AltaCursoFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.AltaInstitutoFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.AltaUsuarioFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.ConsultaUsuarioFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.ConsultaCursoFrame;

/**
 *
 * @author fede1
 */

public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        altaUsuarioMenuItem = new javax.swing.JMenuItem();
        consultaUsuarioMenuItem = new javax.swing.JMenuItem();
        modificarDatosUsuarioMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AltaCursoMenuItem = new javax.swing.JMenuItem();
        ConsultaCursoMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AltaInstitutoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1093, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        jMenu1.setText("Usuarios");

        altaUsuarioMenuItem.setText("Alta Usuario");
        altaUsuarioMenuItem.addActionListener(this::altaUsuarioMenuItemActionPerformed);
        jMenu1.add(altaUsuarioMenuItem);

        consultaUsuarioMenuItem.setText("Consulta de Usuario");
        consultaUsuarioMenuItem.addActionListener(this::consultaUsuarioMenuItemActionPerformed);
        jMenu1.add(consultaUsuarioMenuItem);

        modificarDatosUsuarioMenuItem.setText("Modificar Datos de Usuario");
        jMenu1.add(modificarDatosUsuarioMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cursos");

        AltaCursoMenuItem.setText("Alta de Curso");
        AltaCursoMenuItem.addActionListener(this::AltaCursoMenuItemActionPerformed);
        jMenu2.add(AltaCursoMenuItem);

        ConsultaCursoMenuItem.setText("Consulta de Curso");
        ConsultaCursoMenuItem.addActionListener(this::ConsultaCursoMenuItemActionPerformed);
        jMenu2.add(ConsultaCursoMenuItem);

        jMenu4.setText("Ediciones");

        jMenuItem10.setText("Alta Edicion");
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Consulta de edición");
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Inscripción a edición");
        jMenu4.add(jMenuItem12);

        jMenu2.add(jMenu4);

        jMenu5.setText("Programas");

        jMenuItem1.setText("Crear Programa");
        jMenu5.add(jMenuItem1);

        jMenuItem4.setText("Agregar Curso a Programa");
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Consulta de Programa");
        jMenu5.add(jMenuItem5);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Institucion");

        AltaInstitutoMenuItem.setText("Alta Instituto");
        AltaInstitutoMenuItem.addActionListener(this::AltaInstitutoMenuItemActionPerformed);
        jMenu3.add(AltaInstitutoMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaCursoMenuItemActionPerformed
        // TODO add your handling code here:
        AltaCursoFrame frame = new AltaCursoFrame();
        frame.setResizable(true);
        frame.setClosable(true);
        frame.setMaximizable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();
    }//GEN-LAST:event_AltaCursoMenuItemActionPerformed

    private void altaUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        AltaUsuarioFrame frame = new AltaUsuarioFrame();
        frame.setResizable(true);
        frame.setClosable(true);
        frame.setMaximizable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();
    }//GEN-LAST:event_altaUsuarioMenuItemActionPerformed

    private void consultaUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        ConsultaUsuarioFrame frame = new ConsultaUsuarioFrame();
        frame.setResizable(true);
        frame.setClosable(true);
        frame.setMaximizable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();
    }//GEN-LAST:event_consultaUsuarioMenuItemActionPerformed

    private void AltaInstitutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaInstitutoMenuItemActionPerformed
        // TODO add your handling code here:
        
                // TODO add your handling code here:
        AltaInstitutoFrame frame = new AltaInstitutoFrame();
        frame.setResizable(true);
        frame.setClosable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(false);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();
        
    }//GEN-LAST:event_AltaInstitutoMenuItemActionPerformed

    private void ConsultaCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCursoMenuItemActionPerformed
        // TODO add your handling code here:
        ConsultaCursoFrame frame = new ConsultaCursoFrame();
        frame.setResizable(true);
        frame.setClosable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(false);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();

    }//GEN-LAST:event_ConsultaCursoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AltaCursoMenuItem;
    private javax.swing.JMenuItem AltaInstitutoMenuItem;
    private javax.swing.JMenuItem ConsultaCursoMenuItem;
    private javax.swing.JMenuItem altaUsuarioMenuItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem consultaUsuarioMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem modificarDatosUsuarioMenuItem;
    // End of variables declaration//GEN-END:variables
}
