/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupo3_mat.edEXT.Presentacion.Pantallas;

import com.grupo3_mat.edEXT.Logica.CargadorDatosPrueba;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.AgregarCursoAProgramaFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.AltaCursoFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.AltaEdicionCursoFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.AltaInstitutoFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.AltaUsuarioFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.ConsultaUsuarioFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.ConsultaCursoFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.ConsultaDeProgramaFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.CrearProgramaFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.ConsultaEdicionCursoFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.InscripcionEdicionCursoFrame;
import com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames.ModificarDatosUsuarioFrame;

/**
 *
 * @author fede1
 */

public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        altaUsuarioMenuItem = new javax.swing.JMenuItem();
        consultaUsuarioMenuItem = new javax.swing.JMenuItem();
        modificarDatosUsuarioMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AltaCursoMenuItem = new javax.swing.JMenuItem();
        ConsultaCursoMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AltaECmenuItem = new javax.swing.JMenuItem();
        consultaECmenuItem = new javax.swing.JMenuItem();
        InscripcionECmenuItem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AltaInstitutoMenuItem = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        CargaTotalbtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1093, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        jMenu1.setText("Usuarios");

        altaUsuarioMenuItem.setText("Alta Usuario");
        altaUsuarioMenuItem.addActionListener(this::altaUsuarioMenuItemActionPerformed);
        jMenu1.add(altaUsuarioMenuItem);

        consultaUsuarioMenuItem.setText("Consulta de Usuario");
        consultaUsuarioMenuItem.addActionListener(this::consultaUsuarioMenuItemActionPerformed);
        jMenu1.add(consultaUsuarioMenuItem);

        modificarDatosUsuarioMenuItem.setText("Modificar Datos de Usuario");
        modificarDatosUsuarioMenuItem.addActionListener(this::modificarDatosUsuarioMenuItemActionPerformed);
        jMenu1.add(modificarDatosUsuarioMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cursos");

        AltaCursoMenuItem.setText("Alta de Curso");
        AltaCursoMenuItem.addActionListener(this::AltaCursoMenuItemActionPerformed);
        jMenu2.add(AltaCursoMenuItem);

        ConsultaCursoMenuItem.setText("Consulta de Curso");
        ConsultaCursoMenuItem.addActionListener(this::ConsultaCursoMenuItemActionPerformed);
        jMenu2.add(ConsultaCursoMenuItem);

        jMenu4.setText("Ediciones");

        AltaECmenuItem.setText("Alta Edicion");
        AltaECmenuItem.addActionListener(this::AltaECmenuItemActionPerformed);
        jMenu4.add(AltaECmenuItem);

        consultaECmenuItem.setText("Consulta de edición");
        consultaECmenuItem.addActionListener(this::consultaECmenuItemActionPerformed);
        jMenu4.add(consultaECmenuItem);

        InscripcionECmenuItem.setText("Inscripción a edición");
        InscripcionECmenuItem.addActionListener(this::InscripcionECmenuItemActionPerformed);
        jMenu4.add(InscripcionECmenuItem);

        jMenu2.add(jMenu4);

        jMenu5.setText("Programas");

        jMenuItem1.setText("Crear Programa");
        jMenuItem1.addActionListener(this::CrearProgramaMenuItemActionPerformed);
        jMenu5.add(jMenuItem1);

        jMenuItem4.setText("Agregar Curso a Programa");
        jMenuItem4.addActionListener(this::AgregarCursoAProgramaMenuItemActionPerformed);
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Consulta de Programa");
        jMenuItem5.addActionListener(this::ConsultaDeProgramaMenuItemActionPerformed);
        jMenu5.add(jMenuItem5);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Institucion");

        AltaInstitutoMenuItem.setText("Alta Instituto");
        AltaInstitutoMenuItem.addActionListener(this::AltaInstitutoMenuItemActionPerformed);
        jMenu3.add(AltaInstitutoMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Acciones Extra");

        CargaTotalbtn.setText("Carga Total Automatica");
        CargaTotalbtn.addActionListener(this::CargaTotalbtnActionPerformed);
        jMenu6.add(CargaTotalbtn);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaCursoMenuItemActionPerformed
        // TODO add your handling code here:
        AltaCursoFrame frame = new AltaCursoFrame();
        frame.setClosable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(false);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();
    }//GEN-LAST:event_AltaCursoMenuItemActionPerformed

    private void altaUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        AltaUsuarioFrame frame = new AltaUsuarioFrame();
        frame.setClosable(true);
        frame.setIconifiable(true);
        frame.setResizable(false);
        
        desktopPane.add(frame);
        frame.pack();
        frame.setVisible(true);

        desktopPane.revalidate();
        desktopPane.repaint();
    }//GEN-LAST:event_altaUsuarioMenuItemActionPerformed

    private void consultaUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        ConsultaUsuarioFrame frame = new ConsultaUsuarioFrame();
        frame.setResizable(true);
        frame.setClosable(true);
        frame.setMaximizable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(true);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();
    }//GEN-LAST:event_consultaUsuarioMenuItemActionPerformed

    private void AltaInstitutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaInstitutoMenuItemActionPerformed
        // TODO add your handling code here:
        
                // TODO add your handling code here:
        AltaInstitutoFrame frame = new AltaInstitutoFrame();
        frame.setResizable(true);
        frame.setClosable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(false);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();
        
    }//GEN-LAST:event_AltaInstitutoMenuItemActionPerformed

    private void ConsultaCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCursoMenuItemActionPerformed
        // TODO add your handling code here:
        ConsultaCursoFrame frame = new ConsultaCursoFrame();
        frame.setResizable(true);
        frame.setClosable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(false);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();

    }//GEN-LAST:event_ConsultaCursoMenuItemActionPerformed

    private void CrearProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProgramaMenuItemActionPerformed
        CrearProgramaFrame frame = new CrearProgramaFrame();
        desktopPane.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_CrearProgramaMenuItemActionPerformed

    private void AgregarCursoAProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCursoAProgramaMenuItemActionPerformed
        AgregarCursoAProgramaFrame frame = new AgregarCursoAProgramaFrame();
        desktopPane.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_AgregarCursoAProgramaMenuItemActionPerformed

    private void ConsultaDeProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaDeProgramaMenuItemActionPerformed
        ConsultaDeProgramaFrame frame = new ConsultaDeProgramaFrame();
        desktopPane.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_ConsultaDeProgramaMenuItemActionPerformed

    private void AltaECmenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaECmenuItemActionPerformed
        // TODO add your handling code here:
        AltaEdicionCursoFrame frame = new AltaEdicionCursoFrame();
        frame.setResizable(false);
        frame.setClosable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(false);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();

    }//GEN-LAST:event_AltaECmenuItemActionPerformed

    private void consultaECmenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaECmenuItemActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        ConsultaEdicionCursoFrame frame = new ConsultaEdicionCursoFrame();
        frame.setResizable(false);
        frame.setClosable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(false);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();
    }//GEN-LAST:event_consultaECmenuItemActionPerformed

    private void InscripcionECmenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripcionECmenuItemActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        InscripcionEdicionCursoFrame frame = new InscripcionEdicionCursoFrame();
        frame.setResizable(false);
        frame.setClosable(true);
        frame.setIconifiable(true);
        desktopPane.add(frame);
        frame.setVisible(true);

        try {
            frame.setMaximum(false);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        desktopPane.revalidate();
        desktopPane.repaint();
    }//GEN-LAST:event_InscripcionECmenuItemActionPerformed

    private void modificarDatosUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarDatosUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        ModificarDatosUsuarioFrame frame = new ModificarDatosUsuarioFrame();
        frame.setClosable(true);
        frame.setIconifiable(true);
        frame.setResizable(false);

        desktopPane.add(frame);
        frame.setVisible(true);

        desktopPane.revalidate();
        desktopPane.repaint();
    }//GEN-LAST:event_modificarDatosUsuarioMenuItemActionPerformed

    private void CargaTotalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaTotalbtnActionPerformed
        // TODO add your handling code here:
        // 1. Instanciamos la clase que contiene todos los datos
        CargadorDatosPrueba cargador = new CargadorDatosPrueba();

        try {
            // 2. Ejecutamos la carga masiva
            cargador.cargarDatosTotales();

            // 3. Mostramos un mensaje de éxito en pantalla
            javax.swing.JOptionPane.showMessageDialog(this,
                    "¡Todos los datos de prueba fueron cargados con éxito!",
                    "Carga Completada",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // 4. Deshabilitamos el botón para que no se pueda volver a presionar
            // Nota: Asegúrate de que "CargaTotalbtn" sea el nombre real de la variable de tu botón
            // Si tu botón se llama distinto, cámbialo en la línea de abajo.
            ((javax.swing.JMenuItem) evt.getSource()).setEnabled(false);

        } catch (Exception e) {
            // 5. Si algo falla, le avisamos al usuario por pantalla
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ocurrió un error durante la carga de datos:\n" + e.getMessage(),
                    "Error en la Carga",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CargaTotalbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AltaCursoMenuItem;
    private javax.swing.JMenuItem AltaECmenuItem;
    private javax.swing.JMenuItem AltaInstitutoMenuItem;
    private javax.swing.JMenuItem CargaTotalbtn;
    private javax.swing.JMenuItem ConsultaCursoMenuItem;
    private javax.swing.JMenuItem InscripcionECmenuItem;
    private javax.swing.JMenuItem altaUsuarioMenuItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem consultaECmenuItem;
    private javax.swing.JMenuItem consultaUsuarioMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem modificarDatosUsuarioMenuItem;
    // End of variables declaration//GEN-END:variables
}
