/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames;

import com.grupo3_mat.edEXT.Logica.DataTypes.DTEdicionCurso;
import com.grupo3_mat.edEXT.Logica.Interfaces.IControladorCurso;
import com.grupo3_mat.edEXT.Logica.Interfaces.IControladorInstituto;
import com.grupo3_mat.edEXT.Logica.Interfaces.IControladorEdicion;
import com.grupo3_mat.edEXT.Logica.Interfaces.IControladorUsuario;
import com.grupo3_mat.edEXT.Logica.Fabrica;
import javax.swing.*;
import java.util.List;
import java.time.*;
import java.util.Date;
/**
 *
 * @author benja
 */
public class AltaEdicionCursoFrame extends javax.swing.JInternalFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AltaEdicionCursoFrame.class.getName());
    
    private IControladorCurso icCurso;
    private IControladorInstituto icInstituto;
    private IControladorEdicion icEdicion;
    private IControladorUsuario icUsuario;

    private DefaultListModel<String> listModelDocentes;
    /**
     * Creates new form AltaEdicionCursoFrame
     */
    public AltaEdicionCursoFrame() {
        initComponents();
    
        Fabrica fabrica = Fabrica.getInstance();
        this.icCurso = fabrica.getIControladorCurso();
        this.icInstituto = fabrica.getIControladorInstituto();
        this.icEdicion = fabrica.getIControladorEdicion();
        this.icUsuario = fabrica.getIControladorUsuario();

        listModelDocentes = new DefaultListModel<>();
        listDocentes.setModel(listModelDocentes);
        listDocentes.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        dateChooserFechaPublicacion.setDateFormatString("dd/MM/yyyy");
        dateChooserFechaInicio.setDateFormatString("dd/MM/yyyy");
        dateChooserFechaFin.setDateFormatString("dd/MM/yyyy");

        cargarInstitutos();
    }
    
    //Auxiliares
    private void cargarInstitutos() {
        cmbInstitutos.removeActionListener(this::cmbInstitutosActionPerformed);
        cmbInstitutos.removeAllItems();
    
        List<String> insts = icInstituto.listarInstitutos();
        if (insts != null) {
            for (String inst : insts) {
                cmbInstitutos.addItem(inst);
            }
        }
    
        cmbInstitutos.setSelectedIndex(-1); // Sin selección previa
        cmbInstitutos.addActionListener(this::cmbInstitutosActionPerformed);

        // Estado inicial de controles dependientes
        cmbCursos.removeAllItems();
        cmbCursos.setEnabled(false);
        listModelDocentes.clear();
    }

    private void cargarDocentes() {
        listModelDocentes.clear();
        String instSeleccionado = (String) cmbInstitutos.getSelectedItem();

        if (instSeleccionado != null) {
            List<String> docentes = icUsuario.listarNicknamesDocentesPorInstituto(instSeleccionado);
            if (docentes != null) {
                for (String doc : docentes) {
                    listModelDocentes.addElement(doc);
                }
            }
        }
    }

    private LocalDate convertirALocalDate(Date date) {
        if (date == null) {
            return null;
        }
        return date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    
    private void alSeleccionarInstituto() {
        cmbCursos.removeActionListener(this::cmbCursosActionPerformed);
        cmbCursos.removeAllItems();

        String instSeleccionado = (String) cmbInstitutos.getSelectedItem();

        if (instSeleccionado != null) {
            List<String> cursos = icCurso.listarCursosPorInstituto(instSeleccionado);
            if (cursos != null) {
                for (String c : cursos) {
                    cmbCursos.addItem(c);
                }
            }
            cmbCursos.setSelectedIndex(-1);
            cmbCursos.setEnabled(true);

            // Cargar los docentes pertenecientes a este instituto
            cargarDocentes();
        } else {
            cmbCursos.setEnabled(false);
            listModelDocentes.clear();
        }

        cmbCursos.addActionListener(this::cmbCursosActionPerformed);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelDocentes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkTieneCupo = new javax.swing.JCheckBox();
        txtCupo = new javax.swing.JTextField();
        labelCurso = new javax.swing.JLabel();
        txtNombreEdicion = new javax.swing.JTextField();
        cmbInstitutos = new javax.swing.JComboBox<>();
        labelInstituto = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        cmbCursos = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        labelFechaInicio = new javax.swing.JLabel();
        dateChooserFechaFin = new com.toedter.calendar.JDateChooser();
        labelFechaFin = new javax.swing.JLabel();
        dateChooserFechaPublicacion = new com.toedter.calendar.JDateChooser();
        dateChooserFechaInicio = new com.toedter.calendar.JDateChooser();
        labelFechaPublicacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDocentes = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("Alta de Edición de Curso");
        setName("Alta de Edicioin de Curso"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        labelDocentes.setText("Docentes:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkTieneCupo.setText("Cupo (opcional):");
        chkTieneCupo.addActionListener(this::chkTieneCupoActionPerformed);

        txtCupo.setEnabled(false);

        labelCurso.setText("Curso:");

        txtNombreEdicion.addActionListener(this::txtNombreEdicionActionPerformed);

        cmbInstitutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbInstitutos.addActionListener(this::cmbInstitutosActionPerformed);

        labelInstituto.setText("Instituto:");

        labelNombre.setText("Nombre:");

        cmbCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCursos.addActionListener(this::cmbCursosActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelInstituto)
                            .addComponent(labelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbInstitutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkTieneCupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCupo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInstituto)
                    .addComponent(cmbInstitutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCurso)
                    .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombreEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTieneCupo)
                    .addComponent(txtCupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelFechaInicio.setText("Fecha de inicio:");

        labelFechaFin.setText("Fecha de finalización:");

        labelFechaPublicacion.setText("Fecha de publicación:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelFechaFin)
                    .addComponent(labelFechaPublicacion)
                    .addComponent(labelFechaInicio)
                    .addComponent(dateChooserFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(dateChooserFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooserFechaPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFechaPublicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooserFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(labelFechaInicio)
                .addGap(18, 18, 18)
                .addComponent(dateChooserFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(labelFechaFin)
                .addGap(18, 18, 18)
                .addComponent(dateChooserFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(listDocentes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDocentes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelDocentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEdicionActionPerformed

    private void chkTieneCupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTieneCupoActionPerformed
        boolean seleccionado = chkTieneCupo.isSelected();
        txtCupo.setEnabled(seleccionado);
        if (!seleccionado) {
            txtCupo.setText("");
        }
    }//GEN-LAST:event_chkTieneCupoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            // Validaciones de UI
            String nombreCurso = (String) cmbCursos.getSelectedItem();
            if (nombreCurso == null) {
                throw new Exception("Debe seleccionar un curso.");
            }

            String nombreEdicion = txtNombreEdicion.getText().trim();
            if (nombreEdicion.isEmpty()) {
                throw new Exception("Ingrese el nombre de la Edición.");
            }

            // Obtener las fechas desde los JDateChooser
            Date datePub = dateChooserFechaPublicacion.getDate();
            Date dateIni = dateChooserFechaInicio.getDate();
            Date dateFin = dateChooserFechaFin.getDate();

            // Validar que no estén vacías
            if (datePub == null){
                throw new Exception("Ingrese una fecha de publicación.");
            }
            if(dateIni == null){
                throw new Exception("Ingrese una fecha de inicio.");
            }
            if(dateFin == null){
                throw new Exception("Ingrese una fecha de finalización.");
            }

            // Convertir a LocalDate
            LocalDate fechaPublicacion = convertirALocalDate(datePub);
            LocalDate fechaInicio = convertirALocalDate(dateIni);
            LocalDate fechaFin = convertirALocalDate(dateFin);

            if (fechaFin.isBefore(fechaInicio)) {
                throw new Exception("La fecha de fin no puede ser anterior a la fecha de inicio.");
            }
            if (fechaInicio.isBefore(fechaPublicacion)) {
                throw new Exception("La fecha de inicio no puede ser anterior a la fecha de publicacion.");
            }
            // Parseo de Cupo
            int cupo = 0;

            if (chkTieneCupo.isSelected()) {
                String textoCupo = txtCupo.getText().trim();
                if (textoCupo.isEmpty()) {
                    throw new Exception("Ingrese o deshabilite el cupo.");
                }
    
                try {
                    cupo = Integer.parseInt(textoCupo);
                    if (cupo <= 0) {
                        throw new Exception("El cupo debe ser mayor a 0.");
                    }
                } catch (NumberFormatException e) {
                    throw new Exception("El cupo debe ser un número entero válido.");
                }
            }

            // Docentes seleccionados
            List<String> docentesSeleccionados = listDocentes.getSelectedValuesList();
            if (docentesSeleccionados.isEmpty()) {
                throw new Exception("Debe seleccionar al menos un docente.");
            }
            
            // Construir DataType y llamar al Controlador
            DTEdicionCurso dtEdicion = new DTEdicionCurso(
                nombreEdicion,
                fechaInicio,
                fechaFin,
                cupo,
                0,
                fechaPublicacion,
                docentesSeleccionados
            );

            icEdicion.altaEdicionCurso(nombreCurso, dtEdicion);

            // Éxito: Notificar y cerrar
            JOptionPane.showMessageDialog(this, "La edición del curso se ha registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            dispose();

        } catch (Exception e) {
            // Captura de errores con diálogos
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al Dar de Alta Edición", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbInstitutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInstitutosActionPerformed
        alSeleccionarInstituto();
    }//GEN-LAST:event_cmbInstitutosActionPerformed

    private void cmbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursosActionPerformed
        
    }//GEN-LAST:event_cmbCursosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkTieneCupo;
    private javax.swing.JComboBox<String> cmbCursos;
    private javax.swing.JComboBox<String> cmbInstitutos;
    private com.toedter.calendar.JDateChooser dateChooserFechaFin;
    private com.toedter.calendar.JDateChooser dateChooserFechaInicio;
    private com.toedter.calendar.JDateChooser dateChooserFechaPublicacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelDocentes;
    private javax.swing.JLabel labelFechaFin;
    private javax.swing.JLabel labelFechaInicio;
    private javax.swing.JLabel labelFechaPublicacion;
    private javax.swing.JLabel labelInstituto;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JList<String> listDocentes;
    private javax.swing.JTextField txtCupo;
    private javax.swing.JTextField txtNombreEdicion;
    // End of variables declaration//GEN-END:variables
}
