/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames;

import com.grupo3_mat.edEXT.Logica.Clases.Curso;
import com.grupo3_mat.edEXT.Logica.Clases.ProgramaFormacion;
import com.grupo3_mat.edEXT.Logica.DataTypes.DTProgramaFormacion;
import com.grupo3_mat.edEXT.Logica.Fabrica;
import com.grupo3_mat.edEXT.Logica.Interfaces.IControladorProgramaFormacion;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author fede1
 */
public class ConsultaDeProgramaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaDeProgramaFrame
     */
    public ConsultaDeProgramaFrame() {
        initComponents();
        cargarProgramas();
    }
    
    private void cargarProgramas() {
        try {
            cmbProgramas.removeAllItems();
            IControladorProgramaFormacion icpf = Fabrica.getInstance().getIControladorProgramaFormacion();
            List<ProgramaFormacion> programas = icpf.listarProgramas();
            
            for (ProgramaFormacion p : programas) {
                cmbProgramas.addItem(p.getNombre());
            }            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar programas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);          
        }
            
    }
    public void cargarDatosPrograma(String nombrePrograma) {
        if (nombrePrograma == null || nombrePrograma.isEmpty()) {
            return;
        }

        // Seleccionar en el ComboBox
        cmbProgramas.setSelectedItem(nombrePrograma);

        try {
            IControladorProgramaFormacion icpf = Fabrica.getInstance().getIControladorProgramaFormacion();
            DTProgramaFormacion dt = icpf.consultarPrograma(nombrePrograma);

            if (dt != null) {
                // Desplegar información detallada en el TextArea
                txtDetalles.setText(
                        "Nombre: " + dt.getNombre() + "\n"
                        + "Descripción: " + dt.getDescripcion() + "\n"
                        + "Fecha Inicio: " + (dt.getFechaInicio() != null ? dt.getFechaInicio().toString() : "") + "\n"
                        + "Fecha Fin: " + (dt.getFechaFin() != null ? dt.getFechaFin().toString() : "")
                );

                // Cargar los cursos del programa en el JList
                DefaultListModel<String> model = new DefaultListModel<>();
                if (dt.getCursos() != null) {
                    for (String curso : dt.getCursos()) {
                        model.addElement(curso);
                    }
                }
                listCursos.setModel(model);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar programa: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbProgramas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCursos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Programa");

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbProgramas.addActionListener(this::cmbProgramasActionPerformed);

        txtDetalles.setEditable(false);
        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        jScrollPane1.setViewportView(txtDetalles);

        listCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listCursos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione Programa:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cursos del Programa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgramasActionPerformed
        String nombreSeleccionado = (String) cmbProgramas.getSelectedItem();
        if (nombreSeleccionado == null) return;
        
        try {
            IControladorProgramaFormacion icpf = Fabrica.getInstance().getIControladorProgramaFormacion();
            ProgramaFormacion pf = icpf.seleccionarPrograma(nombreSeleccionado);
            
            //Mostrar los detalles del programa
            txtDetalles.setText("Nombre: " + pf.getNombre() + "\n" + 
            "Descripcion: " + pf.getDescripcion() + "\n" +
            "Fecha Inicio: " + pf.getFechaInicio() + "\n" +
            "Fecha Fin: " + pf.getFechaFin());
            
            //Cargart los cursos asociados en el JList
            DefaultListModel<String> model = new DefaultListModel<>();
            if (pf.getCursos() != null) {
                for(Curso c : pf.getCursos().values()) {
                    model.addElement(c.getNombre());
                }
            }
            listCursos.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmbProgramasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void listCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCursosMouseClicked
        if (evt.getClickCount() == 1) {
            String cursoSeleccionado = listCursos.getSelectedValue();
            
            if(cursoSeleccionado != null) {
                try {
                    ConsultaCursoFrame consultaCurso = new ConsultaCursoFrame();
                    this.getDesktopPane().add(consultaCurso);
                    consultaCurso.setVisible(true);
                    consultaCurso.toFront();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al abrir la consulta del curso: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } 
    }//GEN-LAST:event_listCursosMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cmbProgramas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listCursos;
    private javax.swing.JTextArea txtDetalles;
    // End of variables declaration//GEN-END:variables

    //private void initComponents() {
      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}
}
