/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.grupo3_mat.edEXT.Presentacion.Pantallas.InternalFrames;

import com.grupo3_mat.edEXT.Logica.Clases.Curso;
import com.grupo3_mat.edEXT.Logica.Clases.ProgramaFormacion;
import com.grupo3_mat.edEXT.Logica.DataTypes.DtCurso;
import com.grupo3_mat.edEXT.Logica.DataTypes.DTProgramaFormacion;
import com.grupo3_mat.edEXT.Logica.Fabrica;
import com.grupo3_mat.edEXT.Logica.Interfaces.IControladorProgramaFormacion;
import com.grupo3_mat.edEXT.Presentacion.Utils.GestorImagenes;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author fede1
 */
public class ConsultaDeProgramaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaDeProgramaFrame
     */
    public ConsultaDeProgramaFrame() {
        initComponents();
        cargarProgramas();
    }
    
    private void cargarProgramas() {
        try {
            cmbProgramas.removeAllItems();
            IControladorProgramaFormacion icpf = Fabrica.getInstance().getIControladorProgramaFormacion();
            List<DTProgramaFormacion> programas = icpf.listarProgramas();
            
            for (DTProgramaFormacion p : programas) {
                cmbProgramas.addItem(p.getNombre());
            }            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar programas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);          
        }
            
    }

    private String armarDetallesPrograma(DTProgramaFormacion programa) {
        // Los institutos mostrados son los de los cursos del programa; el docente es quien lo creó.
        return "Nombre: " + programa.getNombre() + "\n"
                + "Descripción: " + programa.getDescripcion() + "\n"
                + "Fecha Inicio: " + programa.getFechaInicio() + "\n"
                + "Fecha Fin: " + programa.getFechaFin() + "\n"
                + "Docente responsable: " + (programa.getNicknameDocente() != null ? programa.getNicknameDocente() : "Sin asignar") + "\n"
                + "Institutos (por cursos): " + String.join(", ", programa.getInstitutos());
    }

    public void cargarDatosPrograma(String nombrePrograma) {
        if (nombrePrograma == null || nombrePrograma.isEmpty()) {
            return;
        }

        // Seleccionar en el ComboBox
        cmbProgramas.setSelectedItem(nombrePrograma);

        try {
            IControladorProgramaFormacion icpf = Fabrica.getInstance().getIControladorProgramaFormacion();
            DTProgramaFormacion dt = icpf.consultarPrograma(nombrePrograma);

            if (dt != null) {
                GestorImagenes.cargarImagenEnLabel(dt.getImagenPath(), lblImg);

                // Desplegar información detallada en el TextArea
                txtDetalles.setText(armarDetallesPrograma(dt) + "\nCategorías: " + String.join(", ", dt.getCategorias()));

                // Cargar los cursos del programa en el JList
                DefaultListModel<String> model = new DefaultListModel<>();
                if (dt.getCursos() != null) {
                    for (String curso : dt.getCursos()) {
                        model.addElement(curso);
                    }
                }
                listCursos.setModel(model);
                
                // Cargar las categorías
                DefaultListModel<String> modelCategorias = new DefaultListModel<>();
                if (dt.getCategorias() != null) {
                    for (String categoria : dt.getCategorias()) {
                        modelCategorias.addElement(categoria);
                    }
                }
                lstCategorias.setModel(modelCategorias);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar programa: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listCursos1 = new javax.swing.JList<>();
        btnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbProgramas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCursos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVerCurso = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList<>();
        jPanel8 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();

        listCursos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCursos1MouseClicked(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Programa");

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbProgramas.addActionListener(this::cmbProgramasActionPerformed);

        txtDetalles.setEditable(false);
        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        jScrollPane1.setViewportView(txtDetalles);

        listCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listCursos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione Programa:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cursos del Programa:");

        btnVerCurso.setText("Ver Curso");
        btnVerCurso.addActionListener(this::btnVerCursoActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Categorías del Programa:");

        jScrollPane3.setViewportView(lstCategorias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerCurso)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen de Perfil"));

        lblImg.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lblImg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(531, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgramasActionPerformed
        String nombreSeleccionado = (String) cmbProgramas.getSelectedItem();
        if (nombreSeleccionado == null) {
            lblImg.setIcon(null);
            lblImg.setText("");
            return;
        }

        try {
            IControladorProgramaFormacion icpf = Fabrica.getInstance().getIControladorProgramaFormacion();
            DTProgramaFormacion pf = icpf.seleccionarPrograma(nombreSeleccionado);

            GestorImagenes.cargarImagenEnLabel(pf.getImagenPath(), lblImg);

            // Mostrar los detalles del programa
                txtDetalles.setText(armarDetallesPrograma(pf) + "\nCategorías: " + String.join(", ", pf.getCategorias()));

            // Cargar los cursos asociados en el JList
            DefaultListModel<String> model = new DefaultListModel<>();
            if (pf.getCursos() != null) {
                for (String nombreCurso : pf.getCursos()) {
                    model.addElement(nombreCurso);
                }
            }
            listCursos.setModel(model);
            
            // Cargar las categorías asociadas
            DefaultListModel<String> modelCategorias = new DefaultListModel<>();
            if (pf.getCategorias() != null) {
                for (String nombreCategoria : pf.getCategorias()) {
                    modelCategorias.addElement(nombreCategoria);
                }
            }
            lstCategorias.setModel(modelCategorias);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmbProgramasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void listCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCursosMouseClicked

    }//GEN-LAST:event_listCursosMouseClicked

    private void btnVerCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCursoActionPerformed
        String cursoSeleccionado = listCursos.getSelectedValue();

        if (cursoSeleccionado == null) {
            JOptionPane.showMessageDialog(
                this, 
                "Seleccione un curso de la lista.", 
                "Atención", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            javax.swing.JDesktopPane desktop = this.getDesktopPane();

            if (desktop != null) {
                // Invoca a ConsultaCursoFrame
                ConsultaCursoFrame consultaCurso = new ConsultaCursoFrame(cursoSeleccionado);
                desktop.add(consultaCurso);
                consultaCurso.setVisible(true);
                consultaCurso.toFront();
                
                try {
                    consultaCurso.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                    // Ignorar restricción de foco si ocurre
                }
            } else {
                JOptionPane.showMessageDialog(
                    this, 
                    "No se pudo acceder al contenedor principal de pantallas.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE
                );
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this, 
                "Error al abrir la consulta del curso: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnVerCursoActionPerformed

    private void listCursos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCursos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listCursos1MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVerCurso;
    private javax.swing.JComboBox<String> cmbProgramas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImg;
    private javax.swing.JList<String> listCursos;
    private javax.swing.JList<String> listCursos1;
    private javax.swing.JList<String> lstCategorias;
    private javax.swing.JTextArea txtDetalles;
    // End of variables declaration//GEN-END:variables

    //private void initComponents() {
      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}
}
